version: '3.2'
services:
  web:
    image: ${IMAGE}
    volumes:
      - /var/props/staging/assets:/app/public/assets
      - /var/props/staging/log:/app/log
    hostname: "netguru.props.staging.web"
    labels:
      - "netguru.appname=props"
      - "netguru.stage=staging"
    env_file: /opt/secrets.env
    command: dumb-init puma -C config/puma.rb

  sidekiq:
    image: ${IMAGE}
    volumes:
      - /var/props/staging/assets:/app/public/assets
      - /var/props/staging/log:/app/log
    hostname: "netguru.props.staging.sidekiq"
    labels:
      - "netguru.appname=props"
      - "netguru.stage=staging"
    command: dumb-init bash -c "bundle exec sidekiq --config ./config/sidekiq.staging.yml | tee -a log/staging.sidekiq.log"

  crono:
    image: ${IMAGE}
    volumes:
      - /var/props/staging/assets:/app/public/assets
      - /var/props/staging/log:/app/log
    hostname: "netguru.props.staging.crono"
    labels:
      - "netguru.appname=props"
      - "netguru.stage=staging"
    command: dumb-init bash -c "bundle exec crono -L log/staging.crono.log run | tail -f log/staging.crono.log"